### ISSUE TITLE
view_type Error

### ISSUE THREAD

**Issue by yashodhalakshana** [voiceittech/VoiceIt2-AndroidSDK#7]
I'm new to VoiceIt. 
I have add 

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

and

implementation 'com.github.voiceittech:VoiceItApi2AndroidSDK:2.1.3'
implementation 'com.github.voiceittech:VoiceIt2-Java:1.5.0'

these two my grade files and. the gradle sync was successes. 

btw when I build the project after adding these I got error. I don't know how to solve it. Please help me 

![image](https://user-images.githubusercontent.com/34935773/79635480-cfced800-818e-11ea-99eb-f58418ca6fa3.png)

**Comment by noelgrover** [comment]
This is because you updated gradle. Do not update gradle and it will compile.
