### ISSUE TITLE
SDK needs to support modern versions of Android

### ISSUE THREAD

**Issue by danieltorrecillas** [voiceittech/VoiceIt2-AndroidSDK#9]
When will the SDK be updated to support modern versions of Android, as a minimum? Currently, this SDK requires `minSdkVersion` of 17. That is Android 4.2 (Jellybean) released in 2012. Google Play services discontinued updates for Jellybean (API levels 16, 17 & 18) in July 2021 (https://android-developers.googleblog.com/2021/07/google-play-services-discontinuing-jelly-bean.html).

A `minSdkVersion` this old holds back VoiceIt's other SDKs that use this SDK as a dependency.

**Comment by noelgrover** [comment]
You can branch off this and change the minSdkVersion. We have customers that need support for older andriod devices that are in the 7-8 year range. This way you can increase the version to 19+
